version: '3.8'

services:
  itmo-sport-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: itmo-sport-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./userdata.json:/app/userdata.json
    environment:
      - NODE_ENV=production
      - PUPPETEER_ARGS=--no-sandbox,--disable-setuid-sandbox,--disable-gpu,--disable-dev-shm-usage
    command: >
      sh -c "node dist/index.js" 